extends: "@redhat-cloud-services/eslint-config-redhat-cloud-services"
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
plugins: 
  - import
rules:
  sort-imports:
  - error
  - ignoreCase: true
    ignoreDeclarationSort: true
  import/order:
  - error
  - groups:
      - builtin
      - external
      - internal
      - sibling
      - parent
      - index
