extends: [
    "plugin:@typescript-eslint/recommended",
  ]

rules:
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/ban-types": off
  "@typescript-eslint/no-explicit-any": warn
  "@typescript-eslint/no-unused-vars": warn
  explicit-module-boundary-types: off
