extends: [
    "plugin:@typescript-eslint/recommended",
  ]

rules:
  "@typescript-eslint/ban-ts-comment":
    - error
    - ts-expect-error: "allow-with-description"
      ts-ignore: "allow-with-description"
      ts-nocheck: true
      ts-check: true
      minimumDescriptionLength: 5
  "@typescript-eslint/ban-types": off
