extends: "@redhat-cloud-services/eslint-config-redhat-cloud-services"
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
plugins: 
  - import
rules:
  import/order:
  - error
  - groups:
    - builtin
    - external
    - internal
    - sibling
    - parent
    - index
    alphabetize:
      order: asc
      caseInsensitive: true
    newlines-between: always
    pathGroups: # ensures the import of React is always on top
    - pattern: react
      group: builtin
      position: before
    pathGroupsExcludedImportTypes:
    - react
  prefer-const:
  - error
  - destructuring: any
