extends: [
    "plugin:jsx-a11y/recommended",
    "@redhat-cloud-services/eslint-config-redhat-cloud-services",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:testing-library/react",
    "plugin:@typescript-eslint/recommended",
    "plugin:react-redux/recommended"
  ]
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
parser: "@typescript-eslint/parser"
plugins:
  - import
rules:
  import/order:
    - error
    - groups:
      - builtin
      - external
      - internal
      - sibling
      - parent
      - index
      alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
      pathGroups: # ensures the import of React is always on top
      - pattern: react
        group: builtin
        position: before
      pathGroupsExcludedImportTypes:
      - react
  prefer-const:
    - error
    - destructuring: any
  no-console: error
  eqeqeq: error
  array-callback-return: warn
  "@typescript-eslint/ban-ts-comment":
    - error
    - ts-expect-error: "allow-with-description"
      ts-ignore: "allow-with-description"
      ts-nocheck: true
      ts-check: true
      minimumDescriptionLength: 5
  "@typescript-eslint/ban-types": off
  # Temporarily disabled
  jsx-a11y/no-autofocus: off
  rulesdir/forbid-pf-relative-imports: off
