extends: [
    "@redhat-cloud-services/eslint-config-redhat-cloud-services",
    "react-app",
    "react-app/jest"
  ]
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
plugins:
  - import
rules:
  rulesdir/forbid-pf-relative-imports: off
  import/order:
    - error
    - groups:
      - builtin
      - external
      - internal
      - sibling
      - parent
      - index
      alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
      pathGroups: # ensures the import of React is always on top
      - pattern: react
        group: builtin
        position: before
      pathGroupsExcludedImportTypes:
      - react
  prefer-const:
    - error
    - destructuring: any
  no-console: 2
  eqeqeq: error
overrides:
  - files: "**/*.ts?(x)"
    parser: "@typescript-eslint/parser"
    extends: ".eslintrc-typescript.yml"
